// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck
export type FluentMessageId =
  | 'add-print-annotation'
  | 'annotation-delete'
  | 'annotation-edit'
  | 'annotations-menu-label'
  | 'annotations-window-title'
  | 'button-cancel'
  | 'button-save'
  | 'dialog-mode-citation'
  | 'dialog-mode-full'
  | 'dialog-mode-label'
  | 'field-color'
  | 'field-comment'
  | 'field-default-locator'
  | 'field-text'
  | 'field-type'
  | 'outline-menu-label'
  | 'outline-window-title'
  | 'placeholder-title'
  | 'pref-section'
  | 'pref-show-works'
  | 'pref-show-works-hint'
  | 'save-failed'
  | 'startup-finish'
  | 'type-highlight'
  | 'type-image'
  | 'type-ink'
  | 'type-note'
  | 'type-text'
  | 'type-underline';
