// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck
export type FluentMessageId =
  | 'annotations-menu-label'
  | 'annotations-window-title'
  | 'dialog-mode-citation'
  | 'dialog-mode-full'
  | 'dialog-mode-label'
  | 'outline-menu-label'
  | 'outline-window-title'
  | 'placeholder-title'
  | 'pref-section'
  | 'pref-show-works'
  | 'pref-show-works-hint'
  | 'startup-finish';
