// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck

// prettier-ignore
declare namespace _ZoteroTypes {
  interface Prefs {
    PluginPrefsMap: {
      "showWorksInAnnotationView": boolean;
      "dialogOutlineView": boolean;
      "citedAnnotations": string;
      "citationOnly": boolean;
      "keepEmptyPlaceholders": boolean;
      "citaviImport": boolean;
      "citaviKeepNotes": boolean;
      "citaviLinkContributions": boolean;
      "citaviLocatorPage": string;
      "citaviLocatorColumn": string;
      "citaviLocatorParagraph": string;
      "citaviLocatorMargin": string;
      "citaviLocatorOther": string;
    };
  }
}
