/**
 * strings — UI texts of the dynamically built organizer window.
 *
 * The organizer builds its DOM in code, so its texts live here (German and
 * English) instead of in Fluent files; menus and preferences use Fluent.
 */

const de = {
  loading: "Lade …",
  tabKnowledge: "Wissen",
  tabTitles: "Titel",
  all: "(Alle)",
  none: "(Ohne Kategorie)",
  addHeading: "Überschrift hinzufügen",
  addSub: "Unterüberschrift hinzufügen",
  up: "Nach oben (Strg+↑)",
  down: "Nach unten (Strg+↓)",
  indent: "Eine Ebene tiefer (Strg+→)",
  outdent: "Eine Ebene höher (Strg+←)",
  rename: "Umbenennen (F2 oder Doppelklick)",
  delete: "Überschrift löschen (Entf)",
  goto: "Gehe zu …",
  export: "Als Notiz exportieren",
  exportTitle:
    "Legt eine neue Zotero-Notiz an: alle Überschriften in Reihenfolge, darunter die zugeordneten Zitate mit Quellenangabe.",
  exportHint:
    "Erzeugt eine Zotero-Notiz mit der Gliederung und allen zugeordneten Zitaten.",
  exportDone: "Notiz angelegt: {h} Überschriften, {n} Einträge.",
  exportNoteTitle: "Gliederung mit Zitaten",
  newHeading: "Neue Überschrift",
  deleteTitle: "Überschrift löschen",
  deleteConfirm:
    "„{title}“ und alle Unterüberschriften löschen? Die {n} Zuordnungs-Tags werden von den Einträgen entfernt.",
  assigned: "{n} Einträge zu „{title}“ hinzugefügt.",
  skipped: "{n} übersprungen (schreibgeschützt oder schon zugeordnet).",
  search: "Suchen …",
  selected: "{n} markiert",
  assignTo: "Zuweisen an … (tippen, Enter)",
  removeFromCategory: "Entfernen",
  removeFromCategoryTitle: "Markierte aus dieser Kategorie entfernen (Entf)",
  sections: "Zwischentitel",
  shown: "{n} angezeigt",
  empty: "Nichts zu zeigen.",
  pickHint:
    "Wähle einen Eintrag. Strg/Umschalt für Mehrfachauswahl, Strg+A für alle.",
  selectAll: "Alle markieren",
  source: "Quelle",
  categories: "Kategorien",
  open: "Zitatstelle öffnen",
  copy: "Zitat kopieren",
  copied: "Kopiert",
  scope: "Sammlung:",
  scopeAll: "Gesamte Bibliothek",
  scopeSub: "inkl. Untersammlungen",
  edit: "Bearbeiten",
  save: "Speichern",
  cancel: "Abbrechen",
  fQuote: "Zitattext",
  fComment: "Kommentar",
  fPlace: "Zitatstelle (z. B. Seite)",
  fLocator: "Locator",
  saved: "Gespeichert.",
  saveFailed: "Nicht gespeichert (schreibgeschützt).",
  dialogOutline: "Nach Gliederung anordnen (FlexAnnotate)",
  dialogEmpty:
    "FlexAnnotate: Noch keine Annotationen einer Gliederung zugeordnet.",
  dialogFilter: "Annotationen filtern …",
  dialogInsert: "In die Zitation einfügen",
  dialogShowPlace: "Zitatstelle anzeigen",
  dialogCited: "Bereits zitiert",
  dialogUncite: "Zitiert-Markierung entfernen",
  dialogMark: "Als zitiert markieren",
  dialogCheckHint: "Klicken, um die Markierung zu entfernen oder zu setzen",
  dialogHint:
    "Klicke eine Annotation, um das Zitat zu sehen. Doppelklick oder + fügt sie ein.",
};

type Key = keyof typeof de;

const en: Record<Key, string> = {
  loading: "Loading …",
  tabKnowledge: "Knowledge",
  tabTitles: "Titles",
  all: "(All)",
  none: "(No category)",
  addHeading: "Add heading",
  addSub: "Add subheading",
  up: "Move up (Ctrl+↑)",
  down: "Move down (Ctrl+↓)",
  indent: "Indent (Ctrl+→)",
  outdent: "Outdent (Ctrl+←)",
  rename: "Rename (F2 or double-click)",
  delete: "Delete heading (Del)",
  goto: "Go to …",
  export: "Export as note",
  exportTitle:
    "Creates a new Zotero note: all headings in order, with the assigned quotes and their sources below.",
  exportHint: "Creates a Zotero note with the outline and all assigned quotes.",
  exportDone: "Note created: {h} headings, {n} entries.",
  exportNoteTitle: "Outline with quotes",
  newHeading: "New heading",
  deleteTitle: "Delete heading",
  deleteConfirm:
    'Delete "{title}" and all subheadings? The {n} assignment tags are removed from the items.',
  assigned: 'Added {n} items to "{title}".',
  skipped: "{n} skipped (read-only or already assigned).",
  search: "Search …",
  selected: "{n} selected",
  assignTo: "Assign to … (type, Enter)",
  removeFromCategory: "Remove",
  removeFromCategoryTitle: "Remove the selected items from this category (Del)",
  sections: "Subheadings",
  shown: "{n} shown",
  empty: "Nothing to show.",
  pickHint: "Pick an entry. Ctrl/Shift for multi-select, Ctrl+A for all.",
  selectAll: "Select all",
  source: "Source",
  categories: "Categories",
  open: "Open citation place",
  copy: "Copy quote",
  copied: "Copied",
  scope: "Collection:",
  scopeAll: "Whole library",
  scopeSub: "incl. subcollections",
  edit: "Edit",
  save: "Save",
  cancel: "Cancel",
  fQuote: "Quote text",
  fComment: "Comment",
  fPlace: "Citation place (e.g. page)",
  fLocator: "Locator",
  saved: "Saved.",
  saveFailed: "Not saved (read-only).",
  dialogOutline: "Arrange by outline (FlexAnnotate)",
  dialogEmpty: "FlexAnnotate: No annotations assigned to an outline yet.",
  dialogFilter: "Filter annotations …",
  dialogInsert: "Insert into the citation",
  dialogShowPlace: "Show citation place",
  dialogCited: "Already cited",
  dialogUncite: "Remove cited mark",
  dialogMark: "Mark as cited",
  dialogCheckHint: "Click to remove or set the mark",
  dialogHint:
    "Click an annotation to see the quote. Double-click or + inserts it.",
};

export function tr(key: Key): string {
  const locale = (Zotero as any).locale || "en-US";
  return String(locale).toLowerCase().startsWith("de") ? de[key] : en[key];
}
